#!/usr/bin/env python3
"""
Auto-injects the NIEd Quiz Light/Dark theme toggle into any dark-themed
quiz HTML file under quizzes/ that doesn't have it yet.

Safe to run repeatedly (idempotent) — files that already contain the
'theme-tgl' marker are skipped untouched.

Usage: python3 automation/inject_theme_toggle.py
Exits with code 0 always; prints which files were changed.
Sets GITHUB_OUTPUT `changed=true/false` when run inside GitHub Actions.
"""
import glob
import os
import re

THEME_CSS = ".theme-tgl{position:fixed;bottom:16px;right:16px;z-index:200;width:46px;height:46px;border-radius:50%;border:2px solid #FF6B00;background:#111827;color:#FF6B00;font-size:19px;cursor:pointer;box-shadow:0 2px 12px rgba(0,0,0,.45);display:flex;align-items:center;justify-content:center;transition:transform .2s}.theme-tgl:active{transform:scale(.9)}body.light-theme{background:#f4f6fb;color:#1a2035}body.light-theme .pw{background:#eef1f8;border-bottom-color:#dde2ee}body.light-theme .pbg{background:#dde2ee}body.light-theme .card{background:linear-gradient(135deg,#ffffff,#f3f5fa);border-color:#d8dde8}body.light-theme .ss{color:#5a6684}body.light-theme .ii{background:#eef1f8;border-color:#dde2ee}body.light-theme .il{color:#5a6684}body.light-theme .rl{background:#eef3fb;border-color:#cfe0f5;color:#48536e}body.light-theme .rl h3{color:#FF6B00}body.light-theme .pw2{background:#f5f7fc;border-color:#e0e4ee}body.light-theme .pl{color:#5a6684}body.light-theme .pb2{background:#eef1f8;border-color:#c9d2e6;color:#5a6684}body.light-theme .pb2.cur{background:#FF6B00;border-color:#FF6B00;color:#fff}body.light-theme .pb2.att{background:#1B2A6B;border-color:#1B2A6B;color:#fff}body.light-theme .pb2.okp{background:#4ADE80;border-color:#4ADE80;color:#000}body.light-theme .pb2.fp{background:#EF4444;border-color:#EF4444;color:#fff}body.light-theme .qt{color:#1a2035}body.light-theme .opt{background:#f7f8fc;border-color:#dde3ee;color:#232c44}body.light-theme .opt:hover:not(.dis){border-color:#FF6B00;background:rgba(255,107,0,.08)}body.light-theme .ok2{background:#e4e8f2;color:#1a2035}body.light-theme .opt.sel .ok2{background:#FF6B00;color:#fff}body.light-theme .opt.sel{border-color:#FF6B00;background:rgba(255,107,0,.08)}body.light-theme .opt.cor{border-color:#16A34A!important;background:rgba(22,163,74,.12)!important}body.light-theme .opt.cor .ok2{background:#16A34A;color:#fff}body.light-theme .opt.wrg{border-color:#EF4444!important;background:rgba(239,68,68,.1)!important}body.light-theme .opt.wrg .ok2{background:#EF4444;color:#fff}body.light-theme .eb{background:#fff7ef;border-color:#FF6B00;color:#5a4a3a}body.light-theme .bprv{background:#eef1f8;color:#48536e;border-color:#c9d2e6}body.light-theme .rc{background:linear-gradient(135deg,#ffffff,#f3f5fa);border-color:#FF6B00}body.light-theme .sb2{background:#eef1f8}body.light-theme .si{background:#f5f7fc;border-color:#e0e4ee}body.light-theme .siq{color:#1a2035}body.light-theme .so.n{background:#eef1f8;border-color:#dde3ee;color:#5a6684}body.light-theme .sie{background:#eef3fb;color:#48536e}body.light-theme .ftr{border-top-color:#e0e4ee;color:#5a6684}body.light-theme .theme-tgl{background:#fff;box-shadow:0 2px 12px rgba(0,0,0,.18)}"

THEME_BODY = "<button id=\"themeTgl\" class=\"theme-tgl\" onclick=\"toggleNiedTheme()\" aria-label=\"थीम बदलें (Light/Dark)\" title=\"थीम बदलें\">🌙</button><script>(function(){var K='niedQuizTheme';window.toggleNiedTheme=function(){var light=document.body.classList.toggle('light-theme');localStorage.setItem(K, light?'light':'dark');var b=document.getElementById('themeTgl');if(b)b.textContent=light?'☀️':'🌙';};var saved=localStorage.getItem(K);if(saved==='light'){document.body.classList.add('light-theme');}var b=document.getElementById('themeTgl');if(b)b.textContent=(saved==='light')?'☀️':'🌙';})();</script>"

# Only touch dark-themed interactive quiz pages generated by the NIEd quiz
# template (identified by this exact body background), never the light-themed
# Daily Current Affairs pages or any unrelated page on the site.
DARK_MARKER = "background:#0a0f1e"

TARGET_GLOBS = ["quizzes/*.html", "ES*.html"]


def find_candidates():
    seen = set()
    for pattern in TARGET_GLOBS:
        for path in glob.glob(pattern):
            if path in seen:
                continue
            seen.add(path)
            yield path


def main():
    changed_files = []
    for path in find_candidates():
        try:
            with open(path, encoding="utf-8") as f:
                content = f.read()
        except Exception:
            continue

        if DARK_MARKER not in content:
            continue  # not one of our dark quiz pages
        if "theme-tgl" in content:
            continue  # already has the toggle
        if "</style>" not in content or "<body>" not in content:
            continue  # not the expected template shape, skip safely

        new_content = content.replace("</style>", THEME_CSS + "\n</style>", 1)
        new_content = new_content.replace("<body>", "<body>" + THEME_BODY, 1)

        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        changed_files.append(path)

    if changed_files:
        print(f"Injected theme toggle into {len(changed_files)} file(s):")
        for f in changed_files:
            print(" -", f)
    else:
        print("No new quiz pages needed the theme toggle.")

    gh_out = os.environ.get("GITHUB_OUTPUT")
    if gh_out:
        with open(gh_out, "a", encoding="utf-8") as f:
            f.write(f"changed={'true' if changed_files else 'false'}\n")


if __name__ == "__main__":
    main()
